site_name: API Guidelines
site_description: 'UKHSA API Guidelines'
site_author: 'UKSHA'
docs_dir: docs/
repo_name: 'ukhsa-collaboration/api-guidelines'
repo_url: 'https://github.com/ukhsa-collaboration/api-guidelines/'
edit_uri: edit/main/docs/

theme:
  name: tech_docs_template
  custom_dir: overrides
  logo: assets/images/logo-ukhsa-landscape-new.svg
  favicon: assets/images/favicon-new.svg
  palette:
    # - primary: black
    #   accent: teal
    - scheme: default
      accent: teal

  features:
    - navigation.instant
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.expand
    #- navigation.indexes
    #- navigation.sections
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.action.view
    #- toc.integrate

extra_css:
  - stylesheets/extra.css
  - stylesheets/pdf.css

markdown_extensions:
  - github-callouts
  - md_in_html
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower

plugins:
  - material/search
  #- search
  - awesome-nav
  - redirects:
      redirect_maps:
        'index.md': 'api-design-guidelines/index.md'
  - git-revision-date-localized:
      enabled: !ENV [MKDOCS_GIT_PROVENANCE_ENABLED, false]
      type: timeago
      enable_creation_date: true
  - git-committers:
      enabled: !ENV [MKDOCS_GIT_PROVENANCE_ENABLED, false]
      repository: ukhsa-collaboration/api-guidelines
      token: !ENV [GITHUB_TOKEN]
      branch: main
  - print-site:
      add_to_navigation: false
      add_cover_page: true
      include_css: true
      path_to_pdf: "ukhsa-api-guidelines.pdf"
      enabled: !ENV [MKDOCS_EXPORTER_PDF_ENABLED, false]
